// ── books.js ──────────────────────────────────────────────────────────────────
// Static book catalogue
// ─────────────────────────────────────────────────────────────────────────────

export const BOOKS = [
  // ── Fiction ────────────────────────────────────────────────────────────────
  {
    id: "b001",
    title: "The Midnight Library",
    author: "Matt Haig",
    category: "Fiction",
    price: 129,
    originalPrice: 499,
    cover: "https://covers.openlibrary.org/b/id/10527843-L.jpg",
    rating: 4.5,
    condition: "Good",
    description:
      "Between life and death there is a library, and within that library, the shelves go on forever.",
  },
  {
    id: "b002",
    title: "Atomic Habits",
    author: "James Clear",
    category: "Self-Help",
    price: 159,
    originalPrice: 599,
    cover: "https://covers.openlibrary.org/b/id/10286124-L.jpg",
    rating: 4.8,
    condition: "Like New",
    description:
      "Tiny changes, remarkable results. The most comprehensive guide on building good habits.",
  },
  {
    id: "b003",
    title: "1984",
    author: "George Orwell",
    category: "Classic",
    price: 89,
    originalPrice: 299,
    cover: "https://covers.openlibrary.org/b/id/8575708-L.jpg",
    rating: 4.7,
    condition: "Good",
    description:
      "A dystopian novel set in a totalitarian society where Big Brother watches everyone.",
  },
  {
    id: "b004",
    title: "The Alchemist",
    author: "Paulo Coelho",
    category: "Fiction",
    price: 99,
    originalPrice: 350,
    cover: "https://covers.openlibrary.org/b/id/8714263-L.jpg",
    rating: 4.6,
    condition: "Like New",
    description:
      "A philosophical novel about a young Andalusian shepherd traveling to Egypt in search of treasure.",
  },
  {
    id: "b005",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    category: "Classic",
    price: 109,
    originalPrice: 399,
    cover: "https://covers.openlibrary.org/b/id/8228691-L.jpg",
    rating: 4.8,
    condition: "Good",
    description:
      "A story about racial injustice and the loss of innocence in the American South.",
  },
  {
    id: "b006",
    title: "Sapiens",
    author: "Yuval Noah Harari",
    category: "Non-Fiction",
    price: 199,
    originalPrice: 699,
    cover: "https://covers.openlibrary.org/b/id/8739161-L.jpg",
    rating: 4.7,
    condition: "Like New",
    description:
      "A brief history of humankind — from the Stone Age to the 21st century.",
  },
  {
    id: "b007",
    title: "Harry Potter and the Philosopher's Stone",
    author: "J.K. Rowling",
    category: "Fantasy",
    price: 149,
    originalPrice: 499,
    cover: "https://covers.openlibrary.org/b/id/10110415-L.jpg",
    rating: 4.9,
    condition: "Like New",
    description:
      "The magical story of a young boy discovering he is a wizard on his 11th birthday.",
  },
  {
    id: "b008",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    category: "Classic",
    price: 79,
    originalPrice: 249,
    cover: "https://covers.openlibrary.org/b/id/8257091-L.jpg",
    rating: 4.4,
    condition: "Acceptable",
    description: "A classic American novel about the mysterious millionaire Jay Gatsby.",
  },
  {
    id: "b009",
    title: "Deep Work",
    author: "Cal Newport",
    category: "Self-Help",
    price: 179,
    originalPrice: 599,
    cover: "https://covers.openlibrary.org/b/id/10451983-L.jpg",
    rating: 4.6,
    condition: "Like New",
    description:
      "Rules for focused success in a distracted world — develop the ability to focus without distraction.",
  },
  {
    id: "b010",
    title: "The Hunger Games",
    author: "Suzanne Collins",
    category: "Fiction",
    price: 119,
    originalPrice: 449,
    cover: "https://covers.openlibrary.org/b/id/8228228-L.jpg",
    rating: 4.6,
    condition: "Good",
    description:
      "In a dark future, two teenagers must fight to the death in a televised spectacle.",
  },
  {
    id: "b011",
    title: "Introduction to Algorithms",
    author: "Cormen et al.",
    category: "Academic",
    price: 299,
    originalPrice: 999,
    cover: "https://covers.openlibrary.org/b/id/8746169-L.jpg",
    rating: 4.8,
    condition: "Good",
    description:
      "The definitive reference on algorithms, used in universities worldwide.",
  },
  {
    id: "b012",
    title: "Dune",
    author: "Frank Herbert",
    category: "Sci-Fi",
    price: 169,
    originalPrice: 549,
    cover: "https://covers.openlibrary.org/b/id/8302946-L.jpg",
    rating: 4.7,
    condition: "Like New",
    description:
      "An epic science fiction novel set on the desert planet Arrakis.",
  },
  {
    id: "b013",
    title: "Rich Dad Poor Dad",
    author: "Robert T. Kiyosaki",
    category: "Self-Help",
    price: 139,
    originalPrice: 449,
    cover: "https://covers.openlibrary.org/b/id/10475456-L.jpg",
    rating: 4.4,
    condition: "Acceptable",
    description:
      "What the rich teach their kids about money that the poor and middle class do not!",
  },
  {
    id: "b014",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    category: "Classic",
    price: 69,
    originalPrice: 229,
    cover: "https://covers.openlibrary.org/b/id/8739161-L.jpg",
    rating: 4.7,
    condition: "Good",
    description:
      "A romantic novel of manners, following the story of Elizabeth Bennet.",
  },
  {
    id: "b015",
    title: "The Psychology of Money",
    author: "Morgan Housel",
    category: "Non-Fiction",
    price: 189,
    originalPrice: 599,
    cover: "https://covers.openlibrary.org/b/id/12290670-L.jpg",
    rating: 4.8,
    condition: "Like New",
    description:
      "Timeless lessons on wealth, greed, and happiness through 19 short stories.",
  },
  {
    id: "b016",
    title: "Educated",
    author: "Tara Westover",
    category: "Biography",
    price: 159,
    originalPrice: 499,
    cover: "https://covers.openlibrary.org/b/id/9257016-L.jpg",
    rating: 4.8,
    condition: "Like New",
    description:
      "A memoir about a woman who leaves her survivalist family and goes on to earn a PhD from Cambridge University.",
  },
];

export const CATEGORIES = [
  { label: "All", icon: "📚" },
  { label: "Fiction", icon: "📖" },
  { label: "Classic", icon: "🏛️" },
  { label: "Non-Fiction", icon: "🌍" },
  { label: "Self-Help", icon: "✨" },
  { label: "Fantasy", icon: "🧙" },
  { label: "Sci-Fi", icon: "🚀" },
  { label: "Academic", icon: "🎓" },
  { label: "Biography", icon: "👤" },
];
